### ISSUE TITLE
Put multiple 3DS Max plugins into the same solution

### ISSUE THREAD

**Issue by bhouston** [K240/HoudiniEngineFor3dsMax#1]
If you have a look at the CMake setup in this project, it shows how to setup multiple 3DS Max projects into a single solution:

https://github.com/Exocortex/ExocortexCrate

But then I was looking at your CMake code and maybe you've already read through my CMake files structure. :)

**Comment by bhouston** [comment]
I think these are the same exact file:
https://github.com/K240/HoudiniEngineFor3dsMax/blob/master/Max2014/CMakeLists.txt
https://github.com/Exocortex/ExocortexCrate/blob/master/3DSMax/2014/CMakeLists.txt

**Comment by K240** [comment]
Your cmake script  super useful for every 3dsmax developer :)  I follow your style.
But I was thinking about that keep using cmake script or not.  I'm going to change vcproj from cmake script.
