### ISSUE TITLE
Why is ExocortexCrate not mentinoed as the source of much of the CMake & MaxScript code?

### ISSUE THREAD

**Issue by bhouston** [K240/HoudiniEngineFor3dsMax#2]
A lot of the code for this project is based on Exocortex Crate:

https://github.com/K240/HoudiniEngineFor3dsMax/blob/master/MaxScripts/HoudiniEngine_Startup.ms
https://github.com/Exocortex/ExocortexCrate/blob/master/3DSMax/MaxScripts/Exocortex-Startup.ms

https://github.com/K240/HoudiniEngineFor3dsMax/blob/master/CMakeLists.txt#L56
https://github.com/Exocortex/ExocortexCrate/blob/master/3DSMax/CMakeLists.txt#L59

I haven't yet gone through the C++ code but I would guess there are further similarities.

This is a derived project from ExocortexCrate but the license and all mention of ExocortexCrate has been removed.  This is not appropriate and against the license terms of the ExocortexCrate open source project.

**Comment by K240** [comment]
Hi Ben,
I apologize, Your pointed out is correct, I did should be mention to you in advance.

**Comment by K240** [comment]
Thank you for point out about license. I would not like to violate to any license. So, first, I have moved from cmake script to vcproj.
Then, in HoudiniEngine_Startup.ms, I certainly refferred your code with respect to the avoid of the menu of re-registration. However, most parts of "HoudiniEngine_Startup.ms"
are refferred to the official help of 3DS MAX.

http://docs.autodesk.com/3DSMAX/15/ENU/MAXScript-Help/index.html?url=files/GUID-258F6015-6B45-4A87-A7F5-BB091A2AE065.htm,topicNumber=d30e669858

If it is still violate your license, please let me know. I will fix it immediately.

I am sure that your cmake script is beneficial to all of Max developer. I appreciate about your cooperation.

**Comment by bhouston** [comment]
If you use code from the ExocortexCrate project you have to follow the license terms here, which basically means you need to include this license in your license, or link to it:

https://github.com/Exocortex/ExocortexCrate/blob/master/LICENSE.txt

http://Clara.io, our other project uses open source code as well, thus we have this page that links to their license agreements:

https://clara.io/legal/licenses

**Comment by K240** [comment]
I was added a link to the README.
Thank you for pointing it out.
