### ISSUE TITLE
Crashes with 2016sp2, 15.0.313

### ISSUE THREAD

**Issue by ilayshp** [K240/HoudiniEngineFor3dsMax#4]
Hello
I recompile for 3dsmax 2016sp2, h 15.0.313. It crashed at any sop asset
Clearly do not understand how to properly debug plugin.(i set 3dsmax exe and it's working dir)

log from compile
```
1>..\..\HoudiniEngine.cpp(98): warning C4101: 'failure' : unreferenced local variable

1>..\..\HoudiniEngine_input.cpp(633): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
1>..\..\HoudiniEngine_input.cpp(682): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data

1>..\..\HoudiniEngine_mesh.cpp(315): warning C4101: 'e' : unreferenced local variable
```

**Comment by K240** [comment]
Hi ilayshp,

I've build and test with H15.0.313 and 3dsMax2016(sp1), There was no problem.

>Clearly do not understand how to properly debug plugin.(i set 3dsmax exe and it's working dir)
If you have a experience of 3dsmax plugin development, you can debug in the same way.

**Comment by ilayshp** [comment]
Hi
Thank you for reply. I will rollback to sp1. 
> If you have a experience of 3dsmax plug-in development, you can debug in the same way.

have not ;) - i'm mainly c4d user. But I'm having interest in different development of houdini engine.
